version: '3.8'

services:
  # MySQL Database
  joke_db:
    image: mysql:8.0
    container_name: joke_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jokes_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - joke_network

  # Joke Application
  joke_app:
    build: ./expressjs
    container_name: joke_app
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: joke_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: jokes_db
      MYSQL_PORT: 3306
      PORT: 3000
    depends_on:
      - joke_db
    networks:
      - joke_network

  # ETL Consumer Worker
  etl:
    build: ./etl
    container_name: etl
    ports:
      - "3002:3002"
    environment:
      ETL_PORT: 3002
      DB_TYPE: MYSQL
      HOST_NAME: joke_db
      USER_NAME: admin
      PASSWORD: admin
      DATABASE: jokes_db
      MYSQL_PORT: 3306
      RMQ_HOST: 10.0.1.5
      QUEUE_NAME: jokes-queue
    depends_on:
      - joke_db
    networks:
      - joke_network

volumes:
  db_data:

networks:
  joke_network:
    driver: bridge